#!/usr/bin/env bash
# Aurora Sovereign Empire — one-command bootstrap.
#
# Usage (inside the extracted Sovereign-Package folder):
#   chmod +x start-empire.sh
#   ./start-empire.sh
#
# On first run:
#   - Verifies Docker + docker compose are installed.
#   - Generates a local .env if missing (random ADMIN_PASSWORD, etc.).
#   - Builds the app + render-worker images locally.
#   - Boots the stack detached, creates a persistent /data volume.
#   - Prints the live URL and the admin password you just got handed.
#
# On subsequent runs:
#   - Pulls the latest git changes if this dir is a git repo.
#   - Rebuilds only what changed (Docker layer cache).
#   - Restarts the stack, preserving the SQLite volume.
#
# Safe to re-run any time. Idempotent.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

log() { printf "\033[1;36m[empire]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[empire]\033[0m %s\n" "$*" >&2; }
fail() { printf "\033[1;31m[empire]\033[0m %s\n" "$*" >&2; exit 1; }

# ---------- 1. Prerequisites ----------

command -v docker >/dev/null 2>&1 \
  || fail "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"

if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  fail "docker compose plugin is not available. Install Docker 20.10+ with the Compose v2 plugin."
fi

if ! docker info >/dev/null 2>&1; then
  fail "Docker daemon is not reachable. Start it (e.g. 'sudo systemctl start docker') and re-run."
fi

# ---------- 2. Self-update (best-effort) ----------

if [ -d ".git" ] && command -v git >/dev/null 2>&1; then
  log "Pulling latest changes (best-effort)…"
  git pull --ff-only || warn "git pull failed — continuing with current checkout."
fi

# ---------- 3. .env bootstrap ----------

if [ ! -f ".env" ]; then
  log "No .env found. Generating one with a fresh ADMIN_PASSWORD…"
  random() { openssl rand -hex 24 2>/dev/null || head -c 36 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 36; }
  admin_pass="$(random)"
  session_secret="$(random)"
  cat > .env <<ENV
# Generated by start-empire.sh on $(date -u +%FT%TZ)
# Rotate these any time; restart with ./start-empire.sh to apply.

ADMIN_PASSWORD=${admin_pass}
AURORA_SESSION_SECRET=${session_secret}

# Optional — plug in if/when you have them:
# SHOTSTACK_API_KEY=
# OPENAI_API_KEY=
# FLY_API_TOKEN=

# Heartbeat — scripts/heartbeat.sh fires on every ./start-empire.sh.
# Configure any combination of channels:
#
# A) Email via Resend (easiest — just one API key)
# RESEND_API_KEY=re_...
# EMAIL_TO=you@example.com
# EMAIL_FROM=onboarding@resend.dev
#
# B) Email via generic SMTP (Gmail app password, Mailgun, Brevo, etc.)
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=you@gmail.com
# SMTP_PASS=<16-char Gmail app password>
# EMAIL_TO=you@example.com
#
# C) Telegram
# TELEGRAM_BOT_TOKEN=
# TELEGRAM_CHAT_ID=
#
# Common options:
# AURORA_PUBLIC_URL=https://empire.example.com
# HEARTBEAT_INCLUDE_PASSWORD=false  # set true to email the admin password literally (not recommended)

# Encrypted backups (required only if you run scripts/backup-nest.sh).
# BACKUP_GPG_PASSPHRASE=
# BACKUP_DEST=local:./backups

AURORA_NEST_HOST=sovereign-nest
AURORA_NEST_REGION=self-hosted
AURORA_NEST_NAME=$(hostname -s 2>/dev/null || echo sovereign-nest)
ENV
  chmod 600 .env
  log "Wrote .env (permissions 600)."
else
  log ".env already exists — preserving your credentials."
fi

# Export for docker compose to pick up.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

# ---------- 4. Build + launch ----------

log "Building images (uses Docker layer cache — fast after first run)…"
"${COMPOSE[@]}" build

log "Launching the Nest detached…"
"${COMPOSE[@]}" up -d

# Wait up to 90s for /api/providers/health to answer 2xx.
log "Waiting for the brain to come online…"
attempts=0
until curl -fsS "http://127.0.0.1:3000/api/providers/health" >/dev/null 2>&1; do
  attempts=$((attempts + 1))
  if [ $attempts -gt 30 ]; then
    warn "Health check timed out. Recent logs:"
    "${COMPOSE[@]}" logs --tail=50 app || true
    fail "Startup failed. Investigate with: ${COMPOSE[*]} logs app"
  fi
  sleep 3
done

# ---------- 5. Report ----------

printf "\n"
printf "\033[1;32m╔══════════════════════════════════════════════════════════╗\033[0m\n"
printf "\033[1;32m║              🦅  The Empire is online                     ║\033[0m\n"
printf "\033[1;32m╚══════════════════════════════════════════════════════════╝\033[0m\n"
printf "\n"
printf "  App:         \033[1mhttp://localhost:3000\033[0m\n"
printf "  Admin:       \033[1mhttp://localhost:3000/admin/login\033[0m\n"
printf "  Agent:       \033[1mhttp://localhost:3000/admin/agent\033[0m\n"
printf "  Terminal:    \033[1mhttp://localhost:3000/admin/terminal\033[0m\n"
printf "  Nest:        \033[1mhttp://localhost:3000/admin/nest\033[0m\n"
printf "  Worker:      \033[1mhttp://localhost:7860/health\033[0m\n"
printf "\n"
printf "  ADMIN_PASSWORD:  \033[1;33m%s\033[0m\n" "${ADMIN_PASSWORD:-<see .env>}"
printf "  (stored in \033[1m.env\033[0m — keep that file private)\n"
printf "\n"
printf "  Persistence:  docker volume \033[1maurora-data\033[0m  →  /data/aurora.db\n"
printf "  Stop:         \033[1m%s down\033[0m\n" "${COMPOSE[*]}"
printf "  Logs:         \033[1m%s logs -f app\033[0m\n" "${COMPOSE[*]}"
printf "  Re-up:        \033[1m./start-empire.sh\033[0m   (safe to rerun; volume persists)\n"
printf "\n"

# ---------- 6. Heartbeat (best-effort) ----------

heartbeat_configured=no
if [ -n "${RESEND_API_KEY:-}" ] && [ -n "${EMAIL_TO:-}" ]; then heartbeat_configured=yes; fi
if [ -n "${SMTP_HOST:-}" ] && [ -n "${SMTP_USER:-}" ] && [ -n "${SMTP_PASS:-}" ] && [ -n "${EMAIL_TO:-}" ]; then heartbeat_configured=yes; fi
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then heartbeat_configured=yes; fi

if [ "$heartbeat_configured" = "yes" ]; then
  log "Heartbeat channel(s) configured — sending boot ping…"
  HEARTBEAT_EVENT=boot "$here/scripts/heartbeat.sh" || warn "heartbeat failed (non-fatal)"
else
  log "Heartbeat not configured. To enable, set one of:"
  log "  RESEND_API_KEY + EMAIL_TO   (email via Resend)"
  log "  SMTP_HOST + SMTP_USER + SMTP_PASS + EMAIL_TO  (email via SMTP)"
  log "  TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID   (Telegram)"
fi
